config/routes.rb
Documents::Engine.routes.draw do
  resources :documents do
    collection do
      post :search
      get :bulk
    end
  end

  root to: 'dashboard#index'
end

app/models/documents/document.rb
module Documents
  class Document < ActiveRecord::Base
    include Documents::Engine.routes.url_helpers

    belongs_to :owner, polymorphic: true
    attr_accessible :file, :owner, :owner_id, :owner_type, :title, :description, :tag_list

    acts_as_taggable

    mount_uploader :file, BasicDocumentUploader

    def to_s
      File.basename(file.to_s)
    end

    def as_json(options=nil)
      {
        name: read_attribute(:file),
        size: file.size,
        url: file.url,
        delete_url: document_path(id: id),
        delete_type: "DELETE"
      }
    end
  end
end

app/controllers/documents/application_controller.rb
module Documents
  class ApplicationController < ActionController::Base
  end
end

app/controllers/documents/dashboard_controller.rb
require_dependency "documents/application_controller"

module Documents
  class DashboardController < ApplicationController
    def index
    end
  end
end

app/controllers/documents/documents_controller.rb
module Documents
  class DocumentsController < Documents::ApplicationController
    respond_to :html, :json

    def index
      if params[:tag]
        @documents = Documents::Document.tagged_with(params[:tag])
      else
        @documents = Documents::Document.scoped
      end
      respond_with @documents
    end

    def new
      @document = Documents::Document.new
    end

    def create
      @document = Documents::Document.new(params[:document])
      @document.save
      respond_with @document
    end

    def show
      @document = Documents::Document.find(params[:id])
    end

    def edit
      @document = Documents::Document.find(params[:id])
    end

    def update
      @document = Documents::Document.find(params[:id])
      @document.update_attributes(params[:document])
      respond_with @document
    end

    def destroy
      @document = Documents::Document.find(params[:id])
      @document.destroy
      respond_with @document
    end

    def search
      @documents = Documents::Document.where("description like ?", "%#{params[:q]}%")
      render :index
    end

    def bulk
    end

  end
end

app/helpers/documents/application_helper.rb
module Documents
  module ApplicationHelper
  end
end

app/helpers/documents/dashboard_helper.rb
module Documents
  module DashboardHelper
  end
end

app/views/documents/dashboard/index.html.erb
  <h1>Welcome to an example Dashboard for documents</h1>

app/views/documents/documents/_form.html.haml
.title
  = f.label :title
  = f.text_field :title

.description
  = f.label :description
  %br
  = f.text_area :description, rows: 5, cols: 80

.tags
  = f.label :tag_list
  %br
  = f.text_field :tag_list

.owner
  = f.select :owner_type, ActiveRecord::Base.descendants.map(&:to_s)
  = f.text_field :owner_id

= f.file_field :file

app/views/documents/documents/bulk.html.haml
%h1
  Bulk Upload

= form_for Images::Image.new, html: {id: :fileupload} do |f|
  <!-- The fileupload-buttonbar contains buttons to add/delete files and start/cancel the upload -->
  .row.fileupload-buttonbar
    .span7
      <!-- The fileinput-button span is used to style the file input field as button -->
      %span.btn.btn-success.fileinput-button
        %i.icon-plus.icon-white
        %span Add files...
        <input id="image_file" name="image[file]" type="file" multiple>

      - if params[:tag]
        %h3
          automatically tagging these images with
          = surround '"' do
            = params[:tag]
        = f.hidden_field :tag_list, value: params[:tag]

    .span5
      <!-- The global progress bar -->
      .progress.progress-success.progress-striped.active.fade
        .bar{style: "width:0%;"}

  <!-- The loading indicator is shown during image processing -->
  .fileupload-loading

  %br

  <!-- The table listing the files available for upload/download -->
  %table.table.table-striped
    %tbody.files{'data-toggle' => "modal-gallery", 'data-target'=>"#modal-gallery"}


<!-- modal-gallery is the modal dialog used for the image gallery -->
#modal-gallery.modal.modal-gallery.hide.fade{'data-filter'=>":odd"}
  .modal-header
    %a.close{'data-dismiss'=>"modal"} ×
    %h3.modal-title

  .modal-body
    .modal-image
  .modal-footer
    %a.btn.modal-download{target: "_blank"}
      %i.icon-download
      %span Download

    %a.btn.btn-success.modal-play.modal-slideshow{'data-slideshow' => "5000"}
      %i.icon-play.icon-white
      %span Slideshow

    %a.btn.btn-info.modal-prev
      %i.icon-arrow-left.icon-white
      %span Previous

    %a.btn.btn-primary.modal-next
      %span Next
      %i.icon-arrow-right.icon-white



-# :javascript
-#   var fileUploadErrors = {
-#     maxFileSize: 'File is too big',
-#     minFileSize: 'File is too small',
-#     acceptFileTypes: 'Filetype not allowed',
-#     maxNumberOfFiles: 'Max number of files exceeded',
-#     uploadedBytes: 'Uploaded bytes exceed file size',
-#     emptyResult: 'Empty file upload result'
-#   };


<script src="http://blueimp.github.com/JavaScript-Load-Image/load-image.min.js"></script>

<!-- The template to display files available for upload -->
%script#template-upload{type: "text/x-tmpl"}
  :plain
    {% for (var i=0, file; file=o.files[i]; i++) { %}
        <tr class="template-upload fade">
            <td class="preview"><span class="fade"></span></td>
            <td class="name"><span>{%=file.name%}</span></td>
            <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
            {% if (file.error) { %}
                <td class="error" colspan="2"><span class="label label-important">{%=locale.fileupload.error%}</span> {%=locale.fileupload.errors[file.error] || file.error%}</td>
            {% } else if (o.files.valid && !i) { %}
                <td>
                    <div class="progress progress-success progress-striped active"><div class="bar" style="width:0%;"></div></div>
                </td>
                <td class="start">{% if (!o.options.autoUpload) { %}
                    <button class="btn btn-primary">
                        <i class="icon-upload icon-white"></i>
                        <span>{%=locale.fileupload.start%}</span>
                    </button>
                {% } %}</td>
            {% } else { %}
                <td colspan="2"></td>
            {% } %}
            <td class="cancel">{% if (!i) { %}
                <button class="btn btn-warning">
                    <i class="icon-ban-circle icon-white"></i>
                    <span>{%=locale.fileupload.cancel%}</span>
                </button>
            {% } %}</td>
        </tr>
    {% } %}

<!-- The template to display files available for download -->
%script#template-download{type: "text/x-tmpl"}
  :plain
    {% for (var i=0, file; file=o.files[i]; i++) { %}
        <tr class="template-download fade">
            {% if (file.error) { %}
                <td></td>
                <td class="name"><span>{%=file.name%}</span></td>
                <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
                <td class="error" colspan="2"><span class="label label-important">{%=locale.fileupload.error%}</span> {%=locale.fileupload.errors[file.error] || file.error%}</td>
            {% } else { %}
                <td class="preview">{% if (file.thumbnail_url) { %}
                    <a href="{%=file.url%}" title="{%=file.name%}" rel="gallery" download="{%=file.name%}"><img src="{%=file.thumbnail_url%}"></a>
                {% } %}</td>
                <td class="name">
                    <a href="{%=file.url%}" title="{%=file.name%}" rel="{%=file.thumbnail_url&&'gallery'%}" download="{%=file.name%}">{%=file.name%}</a>
                </td>
                <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
                <td colspan="2"></td>
            {% } %}
            <td class="delete">
                <button class="btn btn-danger" data-type="{%=file.delete_type%}" data-url="{%=file.delete_url%}">
                    <i class="icon-trash icon-white"></i>
                    <span>{%=locale.fileupload.destroy%}</span>
                </button>
                <input type="checkbox" name="delete" value="1">
            </td>
        </tr>
    {% } %}

app/views/documents/documents/create.json.haml
= raw Array(@image).to_json

app/views/documents/documents/edit.html.haml
%h1
  Edit Image

= form_for @image do |f|
  = render 'form', f: f
  .actions
    = f.submit

app/views/documents/documents/index.html.haml
- content_for :css do
  :css
    .list_image {
      list-style: none;
    }

    .list_image li {
      float: left;
      height: 200px;
      width: 200px;
      overflow: hidden;
    }

%h1
  Document Index

.actions
  %h3
    Search
  = form_tag search_documents_path do
    = text_field_tag :q
    = submit_tag 'Search'
    = link_to 'Clear', documents_path

%h3
  - if params[:tag]
    Documents tagged with
    = surround("\"") do
      = params[:tag]

  - elsif params[:q]
    Documents with text
    = surround("\"") do
      = params[:q]


- if @documents.present?
  %ul.list.list_document
    - @documents.each do |document|
      %li
        = link_to document, document

- else
  No documents currently.

app/views/documents/documents/new.html.haml
%h1
  New Document

= form_for @document do |f|
  = render 'form', f: f
  .actions
    = f.submit

app/views/documents/documents/show.html.haml
.document
  = link_to @document, @document.file.url, target: :blank

.description
  %strong
    Description
  = @document.description

.owner
  %strong
    Owner
  = @document.owner

%strong
  Tags
- if @document.tags.present?
  %ul.tags
    - @document.tag_list.each do |tag|
      %li
        = link_to tag, documents_path(tag: tag)
- else
  None.

.actions
  = link_to 'Edit', edit_document_path(@document)
  |
  = link_to 'Destroy', document_path(@document), method: :delete, data: {confirm: "Sure you want to delete this document?"}

app/views/layouts/documents/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Documents</title>
  <%= stylesheet_link_tag    "documents/application", :media => "all" %>
  <%= javascript_include_tag "documents/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>